### PR TITLE
Created the Login page for patrols.

### PR DESCRIPTION
**Pull request by deasylie**
## Context
Created the Login page for patrols to login to the web app with an email and password.

Closes

## What Changed?
1. Added the input fields for the users email and password along with the Login button.
2. Added the CPNZ logo to the page
3. Added path to Login page in App.tsx

## How To Review
1. Login page in web/pages/Login.tsx

### CODE REVIEW

**Comment by Bobsters6666** [comment]
Good work Deasy!

Form looks good.

**Some changes from me:**
- Renamed email field to ID
- Added login page functionalities from Raymond

**Comment by raymondyangdev** [comment]
Looks good Deasy!

@Bobsters6666 
I noticed that we're parsing the int from the CPNZ ID in the POST request to the backend now.
I made some changes in my PR in api/auth_util/auth.ts to parse the ID to an int in that fil.
We'll need to fix in the future, so we can potentially open up an issue for this once this has been merged and decide whether we want the backend to accept the ID as a string then convert to int in the backend or vice versa.

Also, I thought we weren't merging package-lock.json files?

Other than that, styling looks really good @deasylie 🤠 !

**Comment by Bobsters6666** [comment]
@raymondyangdev 

Yeah we'll probably change the backend later on to accept a String value and parsing it to int within the backend. But everything should be good for now.

I'll go ahead and remove the package-lock.json file from the commit. I didn't bother to change it because it was just a open and close bracket with nothing inside haha.

**Comment by Bobsters6666** [comment]
OH NVM there was also the entire api/package.lock in there.

I've deleted it

**Pull request merged**
